name: erestro_single_vender_rider
description: A new Flutter project.

publish_to: 'none' 

version: 1.1.1+15

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  connectivity_plus: ^6.0.5 #6.0.4
  internet_connection_checker: ^1.0.0+1
  intl_phone_field: ^3.2.0
  # otp_autofill: ^4.0.0
  sms_autofill: ^2.3.0
  path_provider: ^2.0.15
  pin_code_fields: ^8.0.1
  flutter_bloc: ^9.1.0

  cached_network_image: ^3.1.0+1
  # http: ^0.13.3
  shared_preferences: ^2.0.9
  google_maps_flutter: ^2.1.1
  url_launcher: ^6.0.16
  image: ^4.0.15
  #firebaselogin
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter_html: ^3.0.0-alpha.3
  flutter_local_notifications: ^18.0.1
  #google places
  rxdart: ^0.27.4
  google_maps_webservice: ^0.0.20-nullsafety.0
  geolocator: ^13.0.1 #^12.0.0
  geocoding: ^3.0.0
  location:
  location_geocoder: ^1.0.5
  hive_flutter: ^1.0.0
  hive: ^2.0.4
  image_picker: ^1.2.0
  # launch_review: ^3.0.1
  in_app_review: ^2.0.4
  webview_flutter: ^4.0.6
  pin_input_text_field: ^4.1.1
  permission_handler: ^12.0.1
  provider: ^6.0.2
  share_plus: ^10.0.0 #10.0.0
  flutter_exif_rotation: ^0.5.1
  mime_type: ^1.0.0
  shimmer: ^3.0.0
  flutter_html_to_pdf:
    git:
      url: https://github.com/mohammadhprp/flutter_html_to_pdf2
  open_file: ^3.5.10
  # google_maps_place_picker_mb:
  path_drawing: ^1.0.1
  webview_flutter_android: ^4.3.2
  webview_flutter_wkwebview: ^3.2.0
  image_pixels: ^4.0.2
  google_maps_widget: ^1.0.5+1
  file_picker: ^10.3.3
  image_cropper: ^9.1.0

dependency_overrides:
  intl: ^0.18.0
  http:
  google_api_headers: ^4.0.3
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  # To add assets to your application, add an assets section, like this:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/languages/
  fonts:
      - family: Quicksand
        fonts:
          - asset: assets/font/Quicksand-Regular.ttf
          - asset: assets/font/Quicksand-Bold.ttf
            weight: 700
          - asset: assets/font/Quicksand-SemiBold.ttf
            weight: 600
          - asset: assets/font/Quicksand-Light.ttf
            weight: 300
          - asset: assets/font/Quicksand-Medium.ttf
            weight: 500
